### ISSUE TITLE
About shoujo ramune

### ISSUE THREAD

**Issue by Cosetto** [nel1391/BcsExtractor#2]
Put the tanuki.lst in GARbro and check the _project.bcs but it shows only common route 
![image](https://user-images.githubusercontent.com/81801486/136956792-d55e4ef9-d562-4bd7-b8c9-7ed69f64eae8.png)
[datascn.zip](https://github.com/nel1391/BcsExtractor/files/7330268/datascn.zip)

**Comment by nel1391** [comment]
What seems to be the issue? The heroine routes are shown there. They are 05chie.bcs, 06komako.bcs, and 07tenka.bcs. Those and the common routes should be the script for Shoujo Ramune. The other files there that have garbage hash names should be duplicates of the files in the archive. I don't know why GARBro does that, but it doesn't matter.

You'd extract the named files(ie 06komako.bcs) and then extract the csv by running this:

`bcsextractor.exe extract 06komako.bcs -o csv_directory`

You can then modify the game's text with that csv if you follow steps 3, 4, and 5 on the guide after: https://github.com/nel1391/BcsExtractor#replacing-the-original-scripts

**Comment by Cosetto** [comment]
Ok
