### ISSUE TITLE
Unable to extract

### ISSUE THREAD

**Issue by genosis609** [nel1391/BcsExtractor#4]
I am unable to extract this game's archives, using GarBro, but still no use
the game is 姪少女 from Tanuki Soft ― I'll attached the said archive, if you can extract it that would be great
[datascn.zip](https://github.com/nel1391/BcsExtractor/files/8466343/datascn.zip)

**Comment by genosis609** [comment]
After trying arc unpacker - https://github.com/vn-tools/arc_unpacker/ - I was finally able to acquire the scripts, but now I am unable to extract the scripts, I'll attach the following bcs i got. It would be great if you could extract it
[bcs.zip](https://github.com/nel1391/BcsExtractor/files/8497376/bcs.zip)

**Comment by nel1391** [comment]
Interesting, at a glance it looks like this game uses the same file format for BCS as the Rune games. I originally thought that the Rune games were the only ones that used that old BCS format, but it looks like the really old Tanuki Soft games do as well.

I'll look further, I should be able to get it working if it is the same format as the old Rune games.

**Comment by nel1391** [comment]
The new 1.1 release should extract Mei Shoujo's scripts, and script replacement will work the same way if you follow the steps described in the README.
